Algoritmo "Questao 03"
//3) Fazer um programa que pergunte um valor em Dólares e apresente
//o equivalente em Reais. Considere U$1,00 = R$1,72.

Var
// Seção de Declarações das variáveis 
 dolares, reais: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreval("Insira o valor em Dolares")
 leia(dolares)
 
 escreval(dolares, " dólares correspondem à ", dolares * 1.72, " reais")
//quando você calcula o valor dentro do escreva o valor não fica salvo
Fimalgoritmo